name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install -r src/requirements.txt

    - name: Update README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python src/build.py
        cat README.md

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "me@het.im"
        git config --global user.name "imhet"
        git pull
        git add -A
        git commit -m "updated readme" || exit 0
        git push
